language: java

script:
  - mvn clean install --quiet -B
  - mvn clean verify -Pwildfly10
  - mvn clean verify -Pwildfly8

install: /bin/true

jdk:
  - oraclejdk8

branches:
  only:
    - master

notifications:
  email:
    - matthieu@brouillard.fr