language: java

script:
  - mvn clean install --quiet -B
  - mvn clean verify -Pwildfly10
  - mvn clean verify -Pwildfly8

install: /bin/true

jdk:
  - oraclejdk8

branches:
    except:
        - gh-pages

notifications:
  email:
    - matthieu@brouillard.fr
